version: '3'

services:

  frontend:
    container_name: frontend
    image: django
    pull_policy: never
    build: ./frontend
    volumes:
      - fe-vol:/var/www
    ports:
      - "8000:8000"
    networks:
      - jeseo-net

  frontend-db:
    container_name: frontend-db
    image: postgresql
    pull_policy: never
    build: ./frontend-db
    volumes:
      - fe-db-vol:/var/www
    expose:
      - "5432"
    networks:
      - jeseo-net

networks:
  jeseo-net:
    driver: bridge

volumes:
  fe-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${FE_VOL_PATH}

  fe-db-vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${FE_DB_VOL_PATH}
      
