version: '3'

services:

  frontend:
    container_name: frontend
    image: django
    pull_policy: never
    build: ./frontend
    env_file:
      - .env
    depends_on:
      - frontend_db
    ports:
      - "8000:8000"
    volumes:
      - fe_vol:/var/www/django/
    networks:
      - jeseo_net

  frontend_db:
    container_name: frontend_db
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${FE_DB_USER}
      POSTGRES_PASSWORD: ${FE_DB_PW}
    # pull_policy: never
    # build: 
    #   context: ./frontend/frontend_db
    #   args:
    #     - FE_DB=${FE_DB}
    #     - FE_DB_HOST=${FE_DB_HOST}
    #     - FE_DB_USER=${FE_DB_USER}
    #     - FE_DB_PW=${FE_DB_PW}
    volumes:
      - fe_db_vol:/var/lib/postgresql/data
    expose:
      - "5432"
    networks:
      - jeseo_net

networks:
  jeseo_net:
    driver: bridge

volumes:

  fe_db_vol:
    # driver: local
    # driver_opts:
    #   o: bind
    #   type: none
    #   device: ${FE_DB_VOL_PATH}
      
  fe_vol:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${FE_VOL_PATH}